### ISSUE TITLE
Fails to compile in Arduino IDE 1.8.19

### ISSUE THREAD

**Issue by 61pete** [3KUdelta/ESP32_WebRadio#4]
Failed when compiling at line 92, ESP32Encoder::useInternalWeakPullResistors = UP;

with UP was not declared in this scope, did you mean UDP.

I had a bright spark and scratched through the encoder src files and came up with "puType::up" which seemed logical to me but I've only been coding for a week, so there's that.

When I changed line 92 to ESP32Encoder::useInternalWeakPullResistors = puType::up;
it compiled fine and works great.

If using ESP32 encoder by Kevin Harrimgton V0.10.2 and older then "UP" compiles fine.
If using V0.11.0 or newer then puType::up is needed.
